version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - mysql_data:/var/lib/mysqlfolder
    environment:
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'mypassword'
      MYSQL_DATABASE: 'sokol_db'
    ports:
      - '3306:3306'

  redis:
    image: redis:7-alpine

  worker:
    build: .
    restart: always
    entrypoint: [ "celery", "--workdir=.", "-A", "sokol", "worker", "--concurrency=1" ]
    volumes:
      - ./sokol/:/app

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis', '--port=5555' ]
    ports:
      - "5555:5555"
    depends_on:
      - redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  web:
    build: .
    restart: always
    volumes:
      - ./sokol/:/app
    ports:
     - "5000:5000"
    depends_on:
      - db
      - worker

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  mysql_data:
  static_value:
  media_value:
