# Generated by Django 5.0.2 on 2024-02-22 18:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('in_assembly', 'В сборке'), ('transferred_to_delivery', 'Передаётся в доставку'), ('on_the_way', 'В пути'), ('awaiting_receipt', 'Ожидает получения'), ('received', 'Получен '), ('canceled', 'Отменен')], default='awaiting_payment', max_length=40, verbose_name='Статус заказа')),
                ('customer_last_name', models.CharField(max_length=150, verbose_name='Фамилия заказчика')),
                ('customer_first_name', models.CharField(max_length=150, verbose_name='Имя заказчика')),
                ('customer_patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество заказчика')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Почта заказчика')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Тлефон заказчика')),
                ('customer_vk', models.CharField(blank=True, max_length=150, null=True, verbose_name='VK заказчика')),
                ('customer_telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram заказчика')),
                ('delivery_method', models.CharField(max_length=150, verbose_name='Выбранный способ доставки')),
                ('delivery_region', models.CharField(max_length=150, verbose_name='Область')),
                ('delivery_city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('delivery_street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('delivery_house', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом')),
                ('delivery_flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира')),
                ('delivery_entrance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подъезд')),
                ('delivery_floor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Этаж')),
                ('delivery_intercom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Домофон')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('manager_has_been_notified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Менеджер уведомлен')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ на доставку',
                'verbose_name_plural': 'Заказы на доставку',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('ordered_products', models.TextField(verbose_name='Список заказанных товаров')),
                ('price', models.FloatField(verbose_name='Стоимость заказа в рублях')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('in_assembly', 'В сборке'), ('transferred_to_delivery', 'Передаётся в доставку'), ('on_the_way', 'В пути'), ('awaiting_receipt', 'Ожидает получения'), ('received', 'Получен '), ('canceled', 'Отменен')], default='awaiting_payment', max_length=40, verbose_name='Статус заказа')),
                ('customer_last_name', models.CharField(max_length=150, verbose_name='Фамилия заказчика')),
                ('customer_first_name', models.CharField(max_length=150, verbose_name='Имя заказчика')),
                ('customer_patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество заказчика')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Почта заказчика')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Тлефон заказчика')),
                ('customer_vk', models.CharField(blank=True, max_length=150, null=True, verbose_name='VK заказчика')),
                ('customer_telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram заказчика')),
                ('delivery_method', models.CharField(max_length=150, verbose_name='Выбранный способ доставки')),
                ('delivery_region', models.CharField(max_length=150, verbose_name='Область')),
                ('delivery_city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('delivery_street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('delivery_house', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом')),
                ('delivery_flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира')),
                ('delivery_entrance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подъезд')),
                ('delivery_floor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Этаж')),
                ('delivery_intercom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Домофон')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('manager_has_been_notified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Менеджер уведомлен')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ из магазина',
                'verbose_name_plural': 'Заказы из магазина',
            },
        ),
    ]
